Update test-api.yaml

diff --git a/.github/workflows/test-api.yaml b/.github/workflows/test-api.yaml
--- a/.github/workflows/test-api.yaml
+++ b/.github/workflows/test-api.yaml
@@ -1,47 +1,63 @@
----
 name: API Test
+
 on:
   push:
-    branches:
-      - master
+    branches: [ master ]
   pull_request:
-    branches:
-      - master
+    branches: [ master ]
+  workflow_dispatch:
+    inputs:
+      logLevel:
+        description: 'Log level'
+        required: true
+        default: 'warning'
+        type: choice
+        options:
+        - info
+        - warning
+        - debug
+
 jobs:
   test-api:
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v3
-      - name: Use Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: "18"
-      - name: Install dependencies
-        run: npm ci
-      - name: Run API test
-        env:
-          VITE_USERNAME: ${{ secrets.VITE_USERNAME }}
-        run: >
-          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type:
-          application/json" -H "Username: $VITE_USERNAME"
-          https://expenses-backend-mu.vercel.app/expenses)
+    - uses: actions/checkout@v3
 
-          if [ $response -eq 200 ]; then
-            echo "API test successful"
-          else
-            echo "API test failed with status code $response"
-            exit 1
-          fi
-      - name: Check API response
-        env:
-          VITE_USERNAME: ${{ secrets.VITE_USERNAME }}
-        run: >
-          response=$(curl -s -H "Content-Type: application/json" -H "Username:
-          $VITE_USERNAME" https://expenses-backend-mu.vercel.app/expenses)
+    - name: Use Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '18'
 
-          if echo "$response" | jq empty; then
-            echo "API returned valid JSON"
-          else
-            echo "API did not return valid JSON"
-            exit 1
-          fi
+    - name: Install dependencies
+      run: npm ci
+
+    - name: Run API test
+      env:
+        VITE_USERNAME: ${{ secrets.VITE_USERNAME }}
+      run: |
+        response=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -H "Username: $VITE_USERNAME" https://expenses-backend-mu.vercel.app/expenses)
+        if [ $response -eq 200 ]; then
+          echo "API test successful"
+        else
+          echo "API test failed with status code $response"
+          exit 1
+        fi
+
+    - name: Check API response
+      env:
+        VITE_USERNAME: ${{ secrets.VITE_USERNAME }}
+      run: |
+        response=$(curl -s -H "Content-Type: application/json" -H "Username: $VITE_USERNAME" https://expenses-backend-mu.vercel.app/expenses)
+        if echo "$response" | jq empty; then
+          echo "API returned valid JSON"
+        else
+          echo "API did not return valid JSON"
+          exit 1
+        fi
+        if [ $(echo "$response" | jq length) -gt 0 ]; then
+          echo "API returned non-empty array"
+        else
+          echo "API returned empty array"
+          exit 1
+        fi
